In [1]:
from sklearn.model_selection import KFold

In [2]:
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [3]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8]):
    print(train_index , test_index)

[3 4 5 6 7] [0 1 2]
[0 1 2 6 7] [3 4 5]
[0 1 2 3 4 5] [6 7]


In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
from sklearn.datasets import load_digits

In [7]:
digits = load_digits()

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train , x_test , y_train , y_test = train_test_split(digits.data , digits.target , test_size=0.3)

In [10]:
lr = LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)


C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9555555555555556

In [11]:
svm = SVC()
svm.fit(x_train , y_train)
svm.score(x_test,y_test)

0.9777777777777777

In [12]:
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9703703703703703

In [13]:
def get_score(model , x_train,x_test , y_train , y_test):
    model.fit(x_train , y_train)
    return model.score(x_test , y_test)

In [ ]:
get_score(LogisticRegression() , x_train , x_test , y_train , y_test)

In [ ]:
get_score(SVC() , x_train , x_test , y_train , y_test)


In [ ]:
from sklearn.model_selection import StratifiedKFold

In [ ]:
folds = StratifiedKFold(n_splits = 3)


In [ ]:
scores_logistics= []
scores_svm =[]
scores_rf=[]


for train_index, test_index in folds.split(digits.data,digits.target):
    x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                        digits.target[train_index], digits.target[test_index]
    scores_logistics.append(get_score(LogisticRegression (solver='liblinear', multi_class='ovr'), x_train, x_test, y_train, y_test))
    scores_svm.append(get_score (SVC(gamma='auto'), x_train, x_test, y_train, y_test))
    scores_rf.append(get_score (RandomForestClassifier(n_estimators=40), x_train, x_test, y_train, y_test))

In [ ]:
scores_logistics

In [ ]:
scores_rf

In [ ]:
scores_svm

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),digits.data,digits.target ,cv=3)


In [ ]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target ,cv=3)


In [ ]:
cross_val_score(SVC(gamma='auto'),digits.data,digits.target ,cv=3)


In [ ]:
scores1=cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target , cv=3)
np.average(scores1)

In [31]:
scores2=cross_val_score(RandomForestClassifier(n_estimators=20),digits.data,digits.target , cv=10)
np.average(scores2)


np.float64(0.9354531346989446)