In [1]:
from sklearn.model_selection import KFold

In [2]:
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [3]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8]):
    print(train_index , test_index)

[3 4 5 6 7] [0 1 2]
[0 1 2 6 7] [3 4 5]
[0 1 2 3 4 5] [6 7]


In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
from sklearn.datasets import load_digits

In [7]:
digits = load_digits()

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train , x_test , y_train , y_test = train_test_split(digits.data , digits.target , test_size=0.3)

In [10]:
lr = LogisticRegression()

In [11]:
lr.fit(x_train,y_train)

C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [12]:
lr.score(x_test,y_test)

0.9592592592592593

In [13]:
svm = SVC()
svm.fit(x_train , y_train)
svm.score(x_test,y_test)

0.987037037037037

In [14]:
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9666666666666667

In [15]:
def get_score(model , x_train,x_test , y_train , y_test):
    model.fit(x_train , y_train)
    return model.score(x_test , y_test)

In [ ]:
get_score(LogisticRegression() , x_train , x_test , y_train , y_test)

In [ ]:
get_score(SVC() , x_train , x_test , y_train , y_test)


In [16]:
from sklearn.model_selection import StratifiedKFold

In [17]:
folds = StratifiedKFold(n_splits = 3)


In [20]:
scores_logistics= []
scores_svm =[]
scores_rf=[]


for train_index, test_index in folds.split(digits.data,digits.target):
    x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                        digits.target[train_index], digits.target[test_index]
    scores_logistics.append(get_score(LogisticRegression (solver='liblinear', multi_class='ovr'), x_train, x_test, y_train, y_test))
    scores_svm.append(get_score (SVC(gamma='auto'), x_train, x_test, y_train, y_test))
    scores_rf.append(get_score (RandomForestClassifier(n_estimators=40), x_train, x_test, y_train, y_test))

C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


In [21]:
scores_logistics

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [22]:
scores_rf

[0.9365609348914858, 0.9482470784641068, 0.9232053422370617]

In [23]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [25]:
from sklearn.model_selection import cross_val_score

In [26]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),digits.data,digits.target ,cv=3)


C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


array([0.89482471, 0.95325543, 0.90984975])

In [28]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target ,cv=3)


array([0.92320534, 0.94323873, 0.93155259])

In [29]:
cross_val_score(SVC(gamma='auto'),digits.data,digits.target ,cv=3)


array([0.38063439, 0.41068447, 0.51252087])

In [30]:
scores1=cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target , cv=3)
np.average(scores1)

np.float64(0.9371174179187535)

In [31]:
scores2=cross_val_score(RandomForestClassifier(n_estimators=20),digits.data,digits.target , cv=10)
np.average(scores2)


np.float64(0.9354531346989446)